CXX ?= g++
        CXXFLAGS ?= -std=c++17 -O2 -pthread
        TARGET ?= run
        all: $(TARGET)
        $(TARGET): main.cpp
		$(CXX) $(CXXFLAGS) -o $(TARGET) main.cpp
        clean:
		rm -f $(TARGET)
